apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-cache-collector-${BUILD_ENV}
  labels: 
    app: my-deployment-cache-collector-${BUILD_ENV}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment-cache-collector-${BUILD_ENV}

  template:
    metadata:
      labels:
        app: my-deployment-cache-collector-${BUILD_ENV}
        
    spec:
      imagePullSecrets:
      - name: ocir-ipull-secret 

      containers:
      - name: redis-cache
        image: redis:latest
        resources:
          limits:
            memory: 1Gi
            cpu: 200m
          requests:
            memory: 100Mi
            cpu: 20m
        ports:
        - containerPort: 6379
        
      - name: collector
        image: iad.ocir.io/${OCI_NAMESPACE}/data-collection-${BUILD_ENV}:latest
        imagePullPolicy: Always
        env:
          - name: BUILD_ENV
            value: ${BUILD_ENV}
        envFrom:
          - secretRef:
              name: alpaca-keys
          - secretRef:
              name: ${DB_CREDS_KEY}
          - secretRef:
              name: oci-creds
        resources:
          limits:
            memory: 2Gi
            cpu: 400m
          requests:
            memory: 1Gi
            cpu: 200m
        ports:
        - containerPort: 8080
