apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  selector:
    app.kubernetes.io/name: sentiments-frontend
  ports:
  
  - protocol: TCP
    port: 80
    targetPort: 80

  - protocol: TCP
    port: 8000
    targetPort: 8000