apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  selector:
    app.kubernetes.io/name: sentiments-frontend
  ports:
  
  - name: frontend
    protocol: TCP
    port: 80
    targetPort: 80

  - name: backend
    protocol: TCP
    port: 8000
    targetPort: 8000