WITH COUNT_ARTICLES AS (
    SELECT
        SECTOR_ID                AS ID,
        COUNT(TICKERS.SECTOR_ID) AS ARTICLECOUNT
    FROM
             ADMIN.ARTICLETICKERS
        INNER JOIN ADMIN.TICKERS ON ADMIN.TICKERS.ID = ADMIN.ARTICLETICKERS.TICKER_ID
    WHERE
        TICKER <> 'nan'
    GROUP BY
        TICKERS.SECTOR_ID
    ORDER BY
        ARTICLECOUNT DESC
)
SELECT
    COUNT_ARTICLES.ID,
    ADMIN.SECTORS.NAME AS NAME,
    ARTICLECOUNT
FROM
         ADMIN.SECTORS
    INNER JOIN COUNT_ARTICLES ON ADMIN.SECTORS.ID = COUNT_ARTICLES.ID
ORDER BY
    ARTICLECOUNT DESC