WITH COUNT_ARTICLES AS (
    SELECT
        COUNT(ARTICLETICKERS.TICKER_ID) AS ARTICLECOUNT,
        ARTICLETICKERS.TICKER_ID
    FROM
        ADMIN.ARTICLETICKERS
    GROUP BY
        ARTICLETICKERS.TICKER_ID
    ORDER BY
        ARTICLECOUNT DESC
)
SELECT
    ID,
    TICKER,
    COMPANY_NAME,
    ARTICLECOUNT
FROM
         ADMIN.TICKERS
    INNER JOIN COUNT_ARTICLES ON ADMIN.TICKERS.ID = COUNT_ARTICLES.TICKER_ID
WHERE
    TICKER <> 'nan'
ORDER BY
    ARTICLECOUNT DESC