WITH COUNT_ARTICLES AS (
    SELECT
        COUNT(ARTICLETICKERS.TICKER_ID) AS ARTICLECOUNT,
        ARTICLETICKERS.TICKER_ID
    FROM
        ARTICLETICKERS
    GROUP BY
        ARTICLETICKERS.TICKER_ID
)
SELECT
    ID,
    TICKER,
    COMPANY_NAME
FROM
         TICKERS
    INNER JOIN COUNT_ARTICLES ON TICKERS.ID = COUNT_ARTICLES.TICKER_ID
WHERE
    TICKER <> 'nan'
ORDER BY
    COUNT_ARTICLES.ARTICLECOUNT DESC