WITH COUNT_ARTICLES AS (
    SELECT
        SECTOR_ID                AS ID,
        COUNT(TICKERS.SECTOR_ID) AS ARTICLECOUNT
    FROM
             ARTICLETICKERS
        INNER JOIN TICKERS ON TICKERS.ID = ARTICLETICKERS.TICKER_ID
    WHERE
        TICKER <> 'nan'
    GROUP BY
        TICKERS.SECTOR_ID
    ORDER BY
        ARTICLECOUNT DESC
)
SELECT
    COUNT_ARTICLES.ID AS ID,
    SECTORS.NAME AS NAME,
    NULL,
    ARTICLECOUNT
FROM
         SECTORS
    INNER JOIN COUNT_ARTICLES ON SECTORS.ID = COUNT_ARTICLES.ID