SELECT
    TICKER,
    SENTIMENT_SCORE
FROM
    ADMIN.TICKERS
WHERE
        TICKER <> 'nan'
    AND SENTIMENT_SCORE IS NOT NULL
    AND SENTIMENT_SCORE = 4
ORDER BY
    SENTIMENT_SCORE
FETCH FIRST 6 ROWS ONLY