SELECT
    :FIELD,
    SENTIMENT_SCORE
FROM
    :TABLE
WHERE
        :FIELD <> 'nan'
    AND SENTIMENT_SCORE IS NOT NULL
    AND SENTIMENT_SCORE <= 2
    AND SENTIMENT_SCORE >= 0
ORDER BY
    SENTIMENT_SCORE :ORDER
FETCH FIRST 6 ROWS ONLY