name: Push to OCIR action
description: This action pushes containers to OCIR
inputs:
  build-environment:
    description: This is which environment is being deployed later
    required: true
  directory:
    description: This is the directory that is updated
    required: true

runs: 
  using: composite
  
  steps:
    - name: Login to OCIR
      uses: docker/login-action@v3
      id: login-ocir
      with: 
        registry: ${{ env.OCI_CLI_REGION }}.ocir.io
        username: ${{ env.OCI_CLI_TENANCY }}/hwalker145@gmail.com
        password: ${{ env.OCI_CLI_AUTH_T }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      id: build-push-image      
      with: 
        context: ${{ inputs.directory }}
        build-args: |
          BUILD_ENV=${{ inputs.build-environment }}
        push: true
        tags: ${{ inputs.directory }}-${{ inputs.build-environment }}:latest