name: Build the Front End

on:
  push:
    branches: 
      - develop
      - main
    paths:
      - front-end/**

env: 
  ENVIRONMENT_TAG: ${{ github.ref == 'refs/heads/develop' && 'dev' || 'prod' }}

jobs:
  front-end:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: ./.github/actions/docker-kubectl
        with: 
          build-environment: ${{ env.ENVIRONMENT_TAG }}
          directory: front-end