name: Deploys the Stock Sentiment Analyst app

on:
  push:
    branches: 
      - develop
      - main

env: 
  ENVIRONMENT_TAG: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
  OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
  OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
  OCI_CLI_REGION: ${{ vars.OCI_CLI_REGION }}
  OCI_CLI_AUTH_T: ${{ secrets.OCI_CLI_AUTH_T }}
  OCI_CLI_NAMESPACE: ${{ secrets.OCI_CLI_NAMESPACE }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: 'Sentiments-Env'
    steps:
      - uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        name: Evaluate changes to dirs
        id: dorny-paths-filter
        with:
          filters: |
            backend: 
              back-end/**
            frontend: 
              front-end/**
            collection-cache:
              data-collection/**
          base: ${{ github.ref }}
          ref: ${{ github.ref }}

      - name: Backend build-push
        uses: ./.github/actions/docker-kubectl
        if: contains(steps.dorny-paths-filter.outputs.changes, 'backend')
        with: 
          build-environment: ${{ env.ENVIRONMENT_TAG }}
          directory: back-end
      
      - name: Frontend build-push
        uses: ./.github/actions/docker-kubectl
        if: contains(steps.dorny-paths-filter.outputs.changes,'frontend')
        with: 
          build-environment: ${{ env.ENVIRONMENT_TAG }}
          directory: front-end

      - name: Collection-cache build-push
        uses: ./.github/actions/docker-kubectl
        if: contains(steps.dorny-paths-filter.outputs.changes,'data-collection')
        with: 
          build-environment: ${{ env.ENVIRONMENT_TAG }}
          directory: data-collection

  deploy:
    runs-on: ubuntu-latest
    environment: 'Sentiments-Env'
    needs: build-push
    steps:
      - name: Sign into Oracle Kubernetes Engine
        uses: oracle-actions/configure-kubectl-oke@v1.5.0
        env:
          OCI_CLI_REGION: ${{ vars.OCI_CLI_REGION_NAME }}
        with: 
          cluster: ${{ secrets.OCI_CLUSTER_ID }}

      - name: K8s get cluster context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.OKE_KUBECONFIG }}
          context: ${{ vars.OKE_CONTEXT }}

      - name: K8s inject secrets about DB
        uses: azure/k8s-create-secret@v5
        with:
          secret-name: db-creds-oke-${{ env.ENVIRONMENT_TAG }}
          secret-type: generic
          string-data: |
            {"DB_WALLET_PATH": "Wallet-${{ env.ENVIRONMENT_TAG }}",
            "DB_WALLET_PASS": "${{ env.ENVIRONMENT_TAG == 'dev' && secrets.DB_WALLET_PASS_DEV || secrets.DB_WALLET_PASS_PROD }}",
            "DB_USER": "BACKEND",
            "DB_USER_PASS": "${{ env.ENVIRONMENT_TAG == 'dev' && secrets.DB_USER_PASS_DEV || secrets.DB_USER_PASS_PROD }}",
            "DSN_STRING": "${{ env.ENVIRONMENT_TAG == 'dev' && secrets.DB_DSN_DEV || secrets.DB_DSN_PROD }}"}

      - name: Encoding the private key
        run: echo "ENCODED_KEY_CONTENT=$(echo ${{ env.OCI_CLI_KEY_CONTENT }} | base64)" >> GITHUB_ENV

      - name: K8s inject secrets about OCI CLI
        uses: azure/k8s-create-secret@v5
        with:
          secret-name: oci-creds
          secret-type: generic
          string-data: |
            {"OCI_CLI_USER": "${{ env.OCI_CLI_USER }}",
            "OCI_CLI_TENANCY": "${{ env.OCI_CLI_TENANCY }}",
            "OCI_CLI_FINGERPRINT": "${{ env.OCI_CLI_FINGERPRINT }}",
            "OCI_CLI_KEY_CONTENT": "${{ env.ENCODED_KEY_CONTENT }}",
            "OCI_CLI_REGION": "${{ env.OCI_CLI_REGION }}"}

      - name: K8s inject secrets about Alpaca API
        uses: azure/k8s-create-secret@v5
        with:
          secret-name: alpaca-keys
          secret-type: generic
          string-data: |
            {"API_KEY": "${{ secrets.ALPACA_API_KEY }}",
            "API_SECRET_KEY": "${{ secrets.ALPACA_API_SECRET_KEY }}"}

      - run: ls -la ..

      - name: Trigger deploy to Kubernetes
        env:
          BUILD_ENV: ${{ env.ENVIRONMENT_TAG }}
          DB_CREDS_KEY: DB-creds-OKE-${{ env.ENVIRONMENT_TAG }}
          OCI_NAMESPACE: ${{ secrets.OCI_CLI_NAMESPACE }}
          FRONT_END_HOST: ${{ env.ENVIRONMENT_TAG == 'dev' && 'dev.' || '' }}sentiments.henrywalker.tech
        working-directory: ../k8s
        run: |
          kubectl apply -f frontend-service.yaml

          envsubst <               ingress.yaml | kubectl apply -f 
          envsubst < front-back-deployment.yaml | kubectl apply -f 
          envsubst < collection-deployment.yaml | kubectl apply -f 